# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ee/pages/
image: ruby:2.6

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - cd docs && bundle install && cd ../

test:
  stage: test
  script:
    - cd docs && bundle exec jekyll build -d ../test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - cd docs && bundle exec jekyll build -d ../public
    - apt-get update -yqq && apt-get install -y -qq git curl unzip gnupg rsync
    - ls -la
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - which ssh-keyscan
    - ssh-keyscan -p 2543 144.76.104.209 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -rv -e "ssh -p 2543" ../public/* deploy@144.76.104.209:/var/www/planck6502.com

  artifacts:
    paths:
      - public
  only:
    - master
