title: Planck 6502 computer
email: jfoucher@6px.eu

description: "Planck 6502 is an extensible, open hardware, retro computer based on the 6502 processor designed by Jonathan Foucher."

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://planck6502.com" # the base hostname & protocol for your site
twitter_username: jfoucher 
github_username:  jfoucher
author: "Jonathan Foucher"

# feed:
#   posts_limit: 20

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
    style: compressed
permalink: /news/:year/:month/:day/:title/
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
